export type RecordItem={id:string;kind:string;year:string;title:string;status:string;due:string;assignee:string|null;parent:string|null;category:string;body:string;details:Record<string,any>;revision:number;updated:string;actor:string};
export const categories=['Kế hoạch giáo dục','Kế hoạch cá nhân','Hồ sơ chuyên đề','Dự giờ','Kiểm tra đánh giá','Bồi dưỡng thường xuyên','Minh chứng'];
export const workflow=['Bản nháp','Đã nộp','Chờ kiểm tra','Yêu cầu chỉnh sửa','Đã duyệt','Đã lưu hồ sơ'];
export const complete=(s:string)=>['Đã duyệt','Đã lưu hồ sơ','Hoàn thành'].includes(s);
export const moduleNames:Record<string,string>={dashboard:'Tổng quan',year:'Năm học',member:'Thành viên',assignment:'Phân công chuyên môn',plan:'Kế hoạch',curriculum:'Tiến độ chương trình',meeting:'Họp tổ',activity:'Sinh hoạt chuyên môn',observation:'Dự giờ',document:'Hồ sơ chuyên môn',evidence:'Kho minh chứng',exam:'Ngân hàng đề',task:'Công việc',calendar:'Lịch chuyên môn',report:'Báo cáo & thống kê',ai:'Trợ lý AI',settings:'Cài đặt'};
export function demoRecords():RecordItem[]{const rows:RecordItem[]=[];const add=(id:string,kind:string,title:string,status:string,due='',assignee:string|null=null,category='',details:Record<string,any>={},parent:string|null=null,body='')=>rows.push({id,kind,year:'2026–2027',title,status,due,assignee,category,details,parent,body,revision:1,updated:'2026-09-11T07:30:00Z',actor:'Dữ liệu mẫu'});
const names=['Nguyễn Thị Mai','Nguyễn Văn An','Trần Thị Hương','Lê Minh Tuấn','Phạm Thu Hà','Võ Hoàng Nam','Đặng Ngọc Lan','Bùi Thanh Bình','Đỗ Thị Linh','Hoàng Minh Đức','Lý Thanh Thảo','Trương Quốc Huy'];
names.forEach((n,i)=>{add('m'+i,'member',n,'Đang công tác','','','',{subject:['Toán','Khoa học tự nhiên','Tin học'][i%3],role:i===0?'Tổ trưởng':i===1?'Tổ phó':'Giáo viên',email:'',classes:['6A1, 6A2','7A1, 7A2','8A1, 9A1'][i%3]});add('as'+i,'assignment',['Toán','Khoa học tự nhiên','Tin học'][i%3]+' · '+['6A1','7A1','8A1'][i%3],'Đang thực hiện','','m'+i,'',{subject:['Toán','Khoa học tự nhiên','Tin học'][i%3],class:['6A1','7A1','8A1'][i%3],periods:12});categories.forEach((c,j)=>{if((i===2&&j===2)||(i===4&&j===1)||(i===7&&j===3))return;add('d'+i+'-'+j,'document',c+' — '+n,(i+j)%7===0?'Chờ kiểm tra':(i+j)%9===0?'Yêu cầu chỉnh sửa':'Đã duyệt','2026-09-'+(15+j),'m'+i,c,{},null,'Nội dung hồ sơ mẫu. Thay bằng tài liệu của tổ khi bắt đầu sử dụng.');});});
['Hoàn thiện kế hoạch giáo dục tháng 9','Bổ sung minh chứng chuyên đề STEM','Rà soát ma trận đề kiểm tra giữa kỳ I','Chuẩn bị nội dung họp tổ tháng 9','Cập nhật tiến độ chương trình khối 8','Hoàn thành phiếu dự giờ tuần 2','Nộp kế hoạch bồi dưỡng thường xuyên','Xây dựng học liệu số môn KHTN'].forEach((n,i)=>add('t'+i,'task',n,i===2?'Hoàn thành':i%2?'Đang thực hiện':'Chưa thực hiện','2026-09-'+(10+i),'m'+(i%5),'',{priority:i<2?'Ưu tiên cao':'Bình thường'}));
add('mt1','meeting','Sinh hoạt tổ chuyên môn tháng 9','Sắp diễn ra','2026-09-15','m0','',{time:'14:00',location:'Phòng hội đồng',attendees:names.slice(0,6),actions:[{title:'Hoàn thiện chuyên đề STEM',assignee:'m1',due:'2026-09-22'}]},null,'1. Đánh giá công tác đầu năm học\n2. Thống nhất kế hoạch tháng 9\n3. Triển khai chuyên đề STEM');
add('ac1','activity','Dạy học STEM: Năng lượng xanh','Đang chuẩn bị','2026-09-18','m1','Chuyên đề',{time:'08:00',location:'Phòng thực hành'});
add('ob1','observation','Dự giờ KHTN · Lớp 8A1','Đã lên lịch','2026-09-22','m2','',{time:'08:45',location:'Lớp 8A1',score:''});
add('pl1','plan','Kế hoạch hoạt động tổ tháng 9','Đang thực hiện','2026-09-30','m0','Tháng',{},null,'Ổn định nề nếp; hoàn thiện kế hoạch giáo dục; tổ chức chuyên đề STEM; kiểm tra hồ sơ đầu năm.');
add('pl2','plan','Kế hoạch năm học 2026–2027','Đã duyệt','2027-05-31','m0','Năm',{},null,'Đổi mới phương pháp dạy học, tăng cường học liệu số, sinh hoạt chuyên môn theo nghiên cứu bài học.');
add('cu1','curriculum','Khoa học tự nhiên · 8A1','Đang thực hiện','','m2','',{done:8,total:140});
add('ex1','exam','Kiểm tra giữa kỳ I · KHTN 8','Bản nháp','2026-10-20','m1','Khoa học tự nhiên',{grade:'8'},null,'Ma trận, đề kiểm tra và đáp án được đính kèm sau khi rà soát.');
add('ev1','evidence','Tài liệu sinh hoạt chuyên môn tháng 9','Bản nháp','','m0','Minh chứng',{},'mt1','Thêm biên bản, hình ảnh và tài liệu cuộc họp tại đây.');
return rows;}
