import { env } from '@/lib/runtime';
import { getSessionUser } from '@/lib/auth';
export class AppError extends Error{constructor(message:string,public status=400){super(message)}}
export function db(){if(!process.env.DATABASE_URL)throw new AppError('Kho dữ liệu chưa được kết nối. Quản trị viên cần hoàn tất cấu hình.',503);return env.DB;}
export async function context(){const user=await getSessionUser();if(!user)throw new AppError('Vui lòng đăng nhập để lưu dữ liệu.',401);const database=db();const email=user.email.toLowerCase();let membership=await database.prepare('SELECT * FROM memberships WHERE email=?').bind(email).first<any>();if(!membership){const wid=user.userId;await database.batch([database.prepare('INSERT OR IGNORE INTO workspaces (id,owner,name,year,school) VALUES (?,?,?,?,?)').bind(wid,user.userId,'Tổ Khoa học tự nhiên','2026–2027','Trường của tôi'),database.prepare('INSERT OR IGNORE INTO memberships (id,workspace,email,role,member) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),wid,email,'Tổ trưởng',null)]);membership=await database.prepare('SELECT * FROM memberships WHERE email=?').bind(email).first<any>();}const workspace=await database.prepare('SELECT * FROM workspaces WHERE id=?').bind(membership.workspace).first<any>();return {user,database,membership,workspace};}
export type Context=Awaited<ReturnType<typeof context>>;
export function manage(c:Context){return ['Tổ trưởng','Tổ phó'].includes(c.membership.role);}
export function canEdit(c:Context,r:any){return manage(c)||(c.membership.role==='Giáo viên'&&c.membership.member&&r.assignee===c.membership.member&&['document','evidence','task','exam','observation'].includes(r.kind));}
export function fail(e:unknown){console.error(e instanceof Error?e.message:'workspace error');return Response.json({error:e instanceof AppError?e.message:'Không thể hoàn tất thao tác. Dữ liệu đang nhập vẫn được giữ lại.'},{status:e instanceof AppError?e.status:500});}
export function parseRecord(r:any){return {...r,details:typeof r.details==='string'?JSON.parse(r.details):r.details};}
export function insert(c:Context,r:any){return c.database.prepare('INSERT INTO records (id,workspace,kind,year,title,status,due,assignee,parent,category,body,details,revision,updated,actor) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(r.id,c.workspace.id,r.kind,r.year,r.title,r.status,r.due,r.assignee,r.parent,r.category,r.body,JSON.stringify(r.details),r.revision,r.updated,c.user.email);}
export function version(c:Context,r:any,note:string){return c.database.prepare('INSERT INTO versions (id,record,revision,snapshot,actor,created,note) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),r.id,r.revision,JSON.stringify(r),c.user.email,r.updated,note);}

export function canRead(c:Context,r:any){const details=typeof r.details==='string'?JSON.parse(r.details):r.details||{};if(c.membership.role==='Khách/Xem')return details.shared===true;if(c.membership.role==='Giáo viên'&&['document','evidence','task','exam','observation'].includes(r.kind))return r.assignee===c.membership.member||details.shared===true;return true;}
